# Generated by Django 5.0.13 on 2025-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Rider', 'Rider'), ('Attendant', 'Attendant')], default='Rider', max_length=10),
        ),
    ]
